import { Analytics } from '@vercel/analytics/next'
import { SpeedInsights } from '@vercel/speed-insights/next'

import '../globals.css'

import { NextIntlClientProvider } from 'next-intl'
import { getLocale } from 'next-intl/server'
import { notFound } from 'next/navigation'

import { ThemeSwitcher, ThemeSync } from '../_components/theme'
import { jetbrainsMono, nunito } from '../_fonts'
import { ThemeScript } from '../_scripts'
import { Provider } from './provider'
import { cn } from '@/lib'
import { hasLocale } from '@/lib/i18n'
import { routing } from '@/lib/i18n/routing'

import type { Metadata } from 'next'
import type { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'JB Pizza',
  description: 'Generated by OpenAI bot',
}

export const generateStaticParams = () => routing.locales.map((locale) => ({ locale }))

interface RootLayoutProps extends LayoutProps<'/[locale]'> {
  children: ReactNode
}

const RootLayout = async ({ children }: RootLayoutProps) => {
  const locale = await getLocale()
  if (!hasLocale(locale)) notFound()

  return (
    <html
      lang={locale}
      className={cn('h-full antialiased', nunito.variable, jetbrainsMono.variable)}
      suppressHydrationWarning
    >
      <head>
        <ThemeScript />
      </head>
      <body className="mx-auto flex max-w-7xl flex-col px-4 sm:py-16">
        <NextIntlClientProvider>
          <Provider>
            <ThemeSync />
            {children}

            <ThemeSwitcher />
          </Provider>
        </NextIntlClientProvider>

        {process.env.NODE_ENV === 'production' && (
          <>
            <Analytics />
            <SpeedInsights />
          </>
        )}
      </body>
    </html>
  )
}

export default RootLayout
