// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  'brand.pizzeria': 'Pizzeria'
  menu: 'Menu'
  'products.pizzas': 'Pizzas'
  'products.breakfasts': 'Breakfasts'
  'products.wings': 'Wings'
  'products.milkshakes': 'Milkshakes'
  'contacts.title': 'Get in touch'
  'contacts.support': 'Customer support'
  'contacts.email': 'Email us'
  'contacts.feedback': 'Feedback'
  'contacts.info': 'Contacts'
  'github.link': 'View on GitHub'
  'policy.privacy': 'Privacy Policy'
  'policy.terms': 'Terms of Service'

  'button.retryOtp': 'Resend code'
  'page.login.otp.retryCountdown': '{seconds, plural, one {Resend code in # second} other {Resend code in # seconds}}'

  'page.login.phone.title': 'Log in'
  'page.login.phone.description': 'Enter your phone number to sign in to your profile'
  'page.login.code.title': 'Verification code'
  'page.login.code.description': 'A verification code has been sent to the provided number'
  'page.catalog.views.all': 'All'
  'page.catalog.views.pizza': 'Pizzas'
  'page.catalog.views.breakfast': 'Breakfasts'
  'page.catalog.views.wings': 'Wings'
  'page.catalog.views.milkshake': 'Milkshakes'

  'pizza.glutenFree': 'Gluten-Free'
  'pizza.vegetarian': 'Vegan'
  'pizza.novelty': 'New'
  'pizza.hit': 'Hit'

  'button.submitPhone': 'Continue'
  'button.login': 'Log in'
  'button.logout': 'Log out'
  'button.cancel': 'Cancel'

  loading: 'Loading'
  retry: 'Retry'

  'price.from': 'from'

  'modal.logout.title': 'Are you sure you want to log out of your profile?'

  'banner.title': 'Enjoy our pizza from anywhere in the world'

  'error.validation.required': 'Field is required'
  'error.validation.length': 'Please fill out the field completely'
  'error.validation.tooLong': 'Value is too long'
  'error.validation.min': 'Value is too small'
  'error.invalidCode': 'Invalid otp code'
  'error.default': 'Something went wrong'
  'error.authorization': 'Authorization error'
  'error.fetch.failed': 'Failed to fetch data'

  'field.login.phone.label': 'Phone number'
  'field.login.code.label': 'Verification code'
}
export default messages
